name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v1

      - name: Prepare output directory
        run: mkdir -p ./dist/hashdata

      - name: Fetch world data
        run: |
          curl -L "https://ourworldoftext.com/worldofhash?fetch=1&min_tileX=-5&min_tileY=-5&max_tileX=4&max_tileY=4" \
          -o ./dist/hashdata/index.json

      - name: Fetch more data
        run: |
          curl -L "https://file.garden/aUYIWVAKvQxCBY-_/database/vector/slimesconjoinedtogether.svg" \
          -o ./dist/index.html

      - name: Fetch more data2
        run: |
          curl -L "https://gdata.vidtape.lol/console_browse" \
          -o ./dist/console_browse
        

      - name: Fetch more data3
        run: |
          curl -L "https://api.websim.com/api/v1/feed/rooms" \
          -o ./dist/websim_browse.json      
          
      - name: Fetch more data3
        run: |
          curl -L "https://api.trimill.xyz/george-bundle/rss.xml" \
          -o ./dist/george.xml      

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4